---
title: "Price Prediction Results Graph"
author: "Conor"
date: "9/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)

Statement <- c("Balance Sheet", "Balance Sheet", "Balance Sheet", "Balance Sheet", "Cash Flow", "Cash Flow", "Cash Flow", "Cash Flow", "Income Statement", "Income Statement", "Income Statement" , "Income Statement", "Merged Statements", "Merged Statements", "Merged Statements", "Merged Statements")
Algorithm  <- c( "Decision Tree", "KNN", "Random Forest", "FCNN", "Decision Tree", "KNN", "Random Forest", "FCNN", "Decision Tree", "KNN", "Random Forest", "FCNN", "Decision Tree", "KNN", "Random Forest", "FCNN")
MAE <- c(35.11, 26.84, 29.86, 39.96, 35.72, 48.39, 32.90, 46.01, 28.95, 36.58, 25.91, 38.37, 30.24, 25.12, 24.26, 32.26)

Std_Error <- c(2.60, 3.05, 2.33, 2.54, 2.18, 3.83, 2.02, 3.02, 2.77, 5.91, 2.40, 6.64, 3.53, 1.82, 2.19, 2.82)

df <- data.frame(Statement, Algorithm, MAE, Std_Error)
df

```




```{r fig.width=10, fig.height=6}
p <- ggplot(df,
            aes(
              x = Statement,
              y = MAE,
              color = Algorithm,
              shape = Algorithm,
              fill = Algorithm,
              group = Algorithm
            )) +
  geom_point(size = 3) +
  
  geom_line(aes(color = Algorithm), size = 1, alpha = 0.7) +
  
  scale_shape_manual(values = c(21, 24, 22, 23), name = "Algorithm",
                     labels = c("Decision Tree", "FCNN", "KNN", "Random Forest") ) +
  
  scale_x_discrete(labels = c("BS", "CF", "IS", "MS"),
                           name = "Statement") +
  
  scale_y_continuous(name = "Mean Absolute Error",
                     breaks = c(25, 30, 35, 40, 45, 50),
                     ) +
  
  scale_colour_manual(values = c("#999999", "#0072B2", "#E69F00", "#000000"), name = "Algorithm",
                      labels = c("Decision Tree", "FCNN", "KNN", "Random Forest")) +
  
  scale_fill_manual(values = c("#999999", "#0072B2", "#E69F00", "#000000"), name = "Algorithm",
                      labels = c("Decision Tree", "FCNN", "KNN", "Random Forest")) +
  
  

  
  
  theme_classic() +
  
  ggtitle("Raw Filings Price Prediction Results")+
  
  theme(axis.text.x = element_text(size = 10), 
      panel.grid.major.y = element_line(size = 0.4,linetype = 'dotted', colour = "lightgrey"),
      plot.title = element_text(hjust = +0.5, vjust = +3),
      axis.title.y = element_text(size = 12, vjust = +4, face = "bold"),
      axis.title.x = element_text(vjust = -2, face = "bold"))


p




```















