---
title: "Untitled"
author: "Conor"
date: "9/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)

Statement <- c("Balance Sheet", "Balance Sheet", "Balance Sheet", "Balance Sheet", "Balance Sheet","Cash Flow", "Cash Flow", "Cash Flow", "Cash Flow", "Cash Flow", "Income Statement", "Income Statement", "Income Statement", "Income Statement" , "Income Statement", "Merged Statements", "Merged Statements", "Merged Statements", "Merged Statements", "Merged Statements")
Algorithm  <- c( "SVM", "Decision Tree", "KNN", "Random Forest", "FCNN", "SVM",  "Decision Tree", "KNN", "Random Forest", "FCNN", "SVM", "Decision Tree", "KNN", "Random Forest", "FCNN", "SVM", "Decision Tree", "KNN", "Random Forest", "FCNN")
Accuracy <- c(0.675, 0.680, 0.694, 0.706, 0.677, 0.678, 0.676, 0.680, 0.685, 0.677, 0.680, 0.688, 0.700, 
         0.699, 0.682, 0.682, 0.710, 0.707, 0.710, 0.688)

Std_Error <- c(0.001, 0.019, 0.008, 0.018, 0.004, 0.008, 0.004, 0.007, 0.014, 0.005, 0.007, 0.015, 0.018, 0.015, 0.004, 0.008,
               0.010, 0.016, 0.012, 0.006)

df <- data.frame(Statement, Algorithm, Accuracy, Std_Error)
df

```

```{r fig.width=10, fig.height=6}
p <- ggplot(df,
            aes(
              x = Statement,
              y = Accuracy,
              color = Algorithm,
              shape = Algorithm,
              fill = Algorithm,
              group = Algorithm
            )) +
  geom_point(size = 3) +
  
  geom_errorbar(aes(ymin = Accuracy - Std_Error, 
                      ymax = Accuracy + Std_Error),
                  width = 0.1, size = 0.75) +
  
  geom_line(aes(color = Algorithm), size = 1, alpha = 0.7) +
  
  scale_shape_manual(values = c(21, 24, 22, 23, 8), name = "Algorithm" ,
                     labels = c("Decision Tree", "FCNN", "KNN", "Random Forest", "SVM")) +
  
  scale_x_discrete(labels = c("BS", "CF", "IS", "MS"),
                           name = "Statement") +
  
  scale_y_continuous(name = "Mean Accuracy",
                     breaks = c(0.65, 0.66, 0.67, 0.68, 0.69, 0.70, 0.71)) +
  
  scale_colour_manual(values = c("#999999", "#0072B2","#E69F00", "#000000", "#009E73"), name = "Algorithm",
                      labels = c("Decision Tree", "FCNN", "KNN", "Random Forest", "SVM")) +
 
  scale_fill_manual(values = c("#999999", "#0072B2","#E69F00", "#000000", "#009E73"), name = "Algorithm",
                     labels = c("Decision Tree","FCNN", "KNN", "Random Forest", "SVM")) +
  
  

  
  
  theme_classic() +
  
  ggtitle("Mean Accuracy with Associated Std. Error")+
  
  theme(axis.text.x = element_text(size = 10), 
      panel.grid.major.y = element_line(size = 0.4,linetype = 'dotted', colour = "lightgrey"),
      plot.title = element_text(hjust = +0.5, vjust = +3),
      axis.title.y = element_text(size = 12, vjust = +4, face = "bold"),
      axis.title.x = element_text(vjust = -2, face = "bold")) +

  facet_wrap(vars(Algorithm))


p




```